In [2]:
import pandas as pd
import plotly.express as px

In [3]:
url = 'movies.csv'
rawdf = pd.read_csv(url)
rawdf.head()
#door Rawdf.head

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
0,Avatar: The Way of Water,7.8,2022,December,PG-13,192,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...","Action, Adventure, Fantasy",New Zealand,"$350,000,000","$2,267,946,983",United States
1,Guillermo del Toro's Pinocchio,7.6,2022,December,PG,117,"Guillermo del Toro, Mark Gustafson","Ewan McGregor, David Bradley, Gregory Mann, Bu...","Animation, Drama, Family",USA,"$35,000,000","$108,967","United States, Mexico, France"
2,Bullet Train,7.3,2022,August,R,127,David Leitch,"Brad Pitt, Joey King, Aaron Taylor Johnson, Br...","Action, Comedy, Thriller",Japan,"$85,900,000","$239,268,602","Japan, United States"
3,The Banshees of Inisherin,7.8,2022,November,R,114,Martin McDonagh,"Colin Farrell, Brendan Gleeson, Kerry Condon, ...","Comedy, Drama",Ireland,Unknown,"$19,720,823","Ireland, United Kingdom, United States"
4,M3gan,6.4,2022,December,PG-13,102,Gerard Johnstone,"Jenna Davis, Amie Donald, Allison Williams, Vi...","Horror, Sci-Fi, Thriller",New Zealand,"$12,000,000","$171,253,910",United States

In [4]:
#load
fig = px.scatter(rawdf, x="Year", y="Rating", color="Country_of_origin", log_y=True, hover_name="Entity", title="Computation used to train notable artificial intelligence systems")
fig.update_traces(marker={'size': 12})

ValueError: Value of 'hover_name' is not the name of a column in 'data_frame'. Expected one of ['Title', 'Rating', 'Year', 'Month', 'Certificate', 'Runtime', 'Directors', 'Stars', 'Genre', 'Filming_location', 'Budget', 'Income', 'Country_of_origin'] but received: Entity